apiVersion: v1
kind: Service
metadata:
  name: comment-service
  labels:
    app: comment-service
    tier: backend
spec:
  selector:
    app: comment-service
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
  labels:
    app: comment-service
    tier: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
        tier: backend
    spec:
      restartPolicy: Always
      containers:
      - name: comment-service
        image: dbogdanovich/comment-service:v0.1.1
        ports:
        - containerPort: 80
