apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
    tier: backend
spec:
  selector:
    app: user-service
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
    tier: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        tier: backend
    spec:
      restartPolicy: Always
      containers:
      - name: user-service
        image: dbogdanovich/user-service:v0.1.2
        ports:
        - containerPort: 80
